<?php namespace Ddup\Payments\Test;

use Ddup\Logger\Aliyun\AliyunLogger;
use Ddup\Logger\Aliyun\Config\AliyunLogStruct;
use Ddup\Payments\Helper\Application;
use Ddup\Payments\Test\TestCase;


class PaymentTest extends TestCase
{

    const pem_key      = __DIR__ . '/Providers/file/keypem.pem';
    const pem_key_prod = __DIR__ . '/Providers/file/keypem-prod.pem';

    /**
     * @var Application
     */
    protected $app;
    protected $open_alilog = false;

    protected function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->app = new Application();

        if ($this->open_alilog) $this->app->logger = new AliyunLogger(new AliyunLogStruct(
            [
                'access_key_id'     => 'LTAIy1VeirRJiZv5',
                'access_key_secret' => '7gi3mlRmSSd8Y70AFUHXcgGeFwu4d2',
                'endpoint'          => 'cn-hangzhou.sls.aliyuncs.com',
                'project'           => 'qyk-v2',
                'store'             => 'dev',
                'topic'             => 'base'
            ]
        ));
    }


}